//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QSDataAccess
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class QuickShoppingDBEntities : DbContext
    {
        public QuickShoppingDBEntities()
            : base("name=QuickShoppingDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<ClothesIMG> ClothesIMGs { get; set; }
        public DbSet<ClothesItem> ClothesItems { get; set; }
        public DbSet<ShoeIMG> ShoeIMGs { get; set; }
        public DbSet<ShoesItem> ShoesItems { get; set; }
        public DbSet<UserSizeCard> UserSizeCards { get; set; }
    }
}
