//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QSDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class ShoesItem
    {
        public ShoesItem()
        {
            this.ShoeIMGs = new HashSet<ShoeIMG>();
        }
    
        public int Id { get; set; }
        public string ShoeName { get; set; }
        public string ShoeKind { get; set; }
        public Nullable<int> EuroShoeSize { get; set; }
    
        public virtual ICollection<ShoeIMG> ShoeIMGs { get; set; }
    }
}
