//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClothesItem
    {
        public ClothesItem()
        {
            this.ClothesIMGs = new HashSet<ClothesIMG>();
        }
    
        public int Id { get; set; }
        public string ClothesName { get; set; }
        public string ClothesKind { get; set; }
        public string InterClothSize { get; set; }
        public Nullable<int> ModelHeight { get; set; }
        public Nullable<int> Amount { get; set; }
    
        public virtual ICollection<ClothesIMG> ClothesIMGs { get; set; }
    }
}
