//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserSizeCard
    {
        public UserSizeCard()
        {
            this.AspNetUsers = new HashSet<AspNetUser>();
        }
    
        public int Id { get; set; }
        public string InterClothSize { get; set; }
        public Nullable<int> EuroShoeSize { get; set; }
        public Nullable<int> Height { get; set; }
        public Nullable<double> Width { get; set; }
        public string UserId { get; set; }
    
        public virtual ICollection<AspNetUser> AspNetUsers { get; set; }
        public virtual AspNetUser AspNetUser { get; set; }
    }
}
